export const projectData = [
	{
		name: "Amazon Clone",
		img: "./img/amazon.png",
		description:
			"This is a Amazon Clone app , build using NextJs ,Redux , NextAuth and Stripe Api. The site is completely responsive on all platforms. NextAuth is used for Authentication. Firebase is used for the storage of media files and other related data. For Styling, Tailwind css is used and Vercel is used for deploying the project. ",
		github: "https://github.com/shumakmanohar/amazon-clone-v1",
		demo: "https://amazon-clone-v1-eight.vercel.app/",
		techUsed: [
			"Next JS",
			"NextAuth",
			"Stripe API",
			"Redux",
			"Tailwind CSS",
			"JavaScript",
			"Vercel",
			,
		],
		latest: false,
		id: "1",
	},
	{
		name: "Open Up",
		img: "./img/openup2.png",
		description:
			"A web app that lets you post your feelings or any message, which will be auto-deleted after 24hrs.✌️ Open Up can be a place where you can share your worst fear, frustration , your secret crush, or fantasies. The user remains completely discreet while posting",
		demo: "https://openup.live/",
		github: "",
		techUsed: [
			"MERN STACK",
			"Next JS",
			"REST API",
			"MongoDB",
			"NodeJs",
			"Heroku",
			"Vercel",
			"MUI",
		],
		latest: false,
		id: "1",
	},
	{
		name: "Hulu - Clone",
		img: "./img/hulu.png",
		description:
			"This is a Hulu Clone app , build using NextJs and themoviedb Api. The site is completely responsive on all platforms, including 4K displays and mobile screens. For Styling, Tailwind css is used and Vercel is used for deploying the project. ",
		github: "https://github.com/shumakmanohar/hulu-clone",
		demo: "https://hulu-clone-2-mu.vercel.app/",
		techUsed: [
			"Next JS",
			"Tailwind CSS",
			"JavaScript",
			"Vercel",
			"themoviedb Api",
		],
		latest: false,
		id: "1",
	},
	{
		name: "Take A BREAK",
		img: "https://play-lh.googleusercontent.com/U-Ycbi0Vj3yEOs0dnUN1P7yvKuyiZMdvNPTCzpTae8KIom90YbV36XSAKHN3zvq58qI=s180-rw",
		description:
			"Take A Break is a desktop and mobile app build using Electron JS and Kotlin it works on 20 - 20 - 20 rule. It is available on both platforms phone and desktop.",
		github: "https://github.com/shumakmanohar/Take-A-Break",
		demo: "https://github.com/shumakmanohar/Take-A-Breakhttps://github.com/shumakmanohar/Take-A-Break",
		techUsed: [
			"HTML n CSS",
			"Electron JS",
			"Android Studio",
			"Jetpack Compose",
		],
		latest: false,
		id: "1",
	},
	{
		name: "Producto",
		img: "https://shumak.netlify.app/imgs/productoLogo.png",
		description: "A todo App build using Android Native with MVVM architecture",
		github: "",
		demo: "https://play.google.com/store/apps/details?id=com.myproducto.producto",
		techUsed: ["Android Studio", "Kotlin", "SQL"],
		latest: false,
		id: "1",
	},
	{
		name: "App Promotion Web",
		img: "./img/apppromote.png",
		description: "Simple webpage build for app promotion",
		github: "",
		demo: "",
		techUsed: ["HTML", "CSS", "JS"],
		latest: false,
		id: "1",
	},
	{
		name: "Food App Design",
		img: "./img/fooddesign.png",
		description: "Simple Figma Design",
		github: "",
		demo: "",
		techUsed: ["Figma"],
		latest: false,
		id: "1",
	},

	{
		name: "ToDo App",
		img: "https://shumak.netlify.app/imgs/d.jpg",
		description:
			"Todo App is a web app , implemented user autenticantion and data storage ",
		github: "https://github.com/shumakmanohar/TodoApp-UserAuthentication",
		demo: "",
		techUsed: ["HTML n CSS", "Express", "NodeJS", "MongoDB"],
		latest: false,
		id: "1",
	},
];
